spring.application.name=jwt-auth

#Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/jwt-auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=120316
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate properties
spring.jpa.hibernate.ddl-auto=update

my.secretKey= This_is_my_secret_key_afdjadsf_adjsfhadjsf_aksdjkfh_akjdfhajdsf_asjdlfhadjkf_ajdfhshaf_adisjfadsjf_alkfdjakdf_asldkjfakdf_adslkfja